language: cpp
compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
    
before_install:
  - eval "${MATRIX_EVAL}"

  - PARENTDIR=$(pwd)
  
  - mkdir $PARENTDIR/build
  - mkdir $PARENTDIR/build-release

  - bash install_cpputest.sh

install:

script:
  - export CC=gcc-8
  - export CXX=g++-8

  - cd $PARENTDIR/build
  - cmake $PARENTDIR/src -DCMAKE_BUILD_TYPE=Debug
  - make -j9

  - cd $PARENTDIR/build-release
  - cmake $PARENTDIR/src -DCMAKE_BUILD_TYPE=Release
  - make -j9
