#ifndef DEL_ASM_INIT_SUPPORT_HPP
#define DEL_ASM_INIT_SUPPORT_HPP


namespace DEL
{
namespace BUILT_IN
{
    
static const std::string ASM_FILE_START = R"asmstart(

;
;   This file was auto generated by the DEL compiler 
;   At the time of this generation DEL compiler was heavily under development
;   by someone who knows very little about compiler design
;       - Josh A. Bosley

.file "DEL_Lang"

.init __del__program__init

)asmstart";

static const std::string ASM_INIT_FUNCTION = R"init(

<__del__program__init:

    ; Allocate the space required for the GS
    ; Codegen put the number in GS 0 for us. 
    mov r0 $0
    ldw r1 $0(gs) 
    mov r2 $0
top:
    add r0 r0 $1    ; Add to the counter
    pushw gs r2     ; Expand GS by a byte
    blt r0 r1 top   ; Loop until complete

    call main       ; Entry to the user's application

    exit
>

)init";


}
}


#endif 